# Generated by Django 5.1.2 on 2024-11-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_customer_alter_products_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
